### PR TITLE
Fix cache clear after changing parameters.

### LINKED ISSUE #538: Parameters form not showing the updated values
### Describe the bug

- Elkarbackup version: v2.0.1, master
- OS: Debian 10 Buster

### Steps to reproduce the behavior

1. Go to the **_Parameters_** section
2. Change a random value: _**i.e. "Max parallel jobs"**_ from 1 to 3
3. Click "Save"

### Expected vs actual behavior

We should see the updated value (3) for "Max parallel jobs"
We see the old value (1), even if the parameters.yaml has been changed correctly.

Workaround: after running a `bin/console cache:clear` the form shows the correct information

### PR DESCRIPTION
**Pull request by elacunza**
This should close #538 .

I'm not particularly fond of the sleep but I can't see how to wait properly. Without the sleep, sometimes the redirected form doesn't show updated values yet.

Also, constructor's first parameter $cacheDir is no longer needed, but I don't know where to unwire it :)

### CODE REVIEW

File: src/Controller/DefaultController.php [hunk 1]
```diff
@@ -186,8 +188,27 @@ protected function isAutoFsAvailable()
...
+            $application->setAutoExit(false);
+            $input = new ArrayInput($commandAndParams);
+            $output = new BufferedOutput();
+            $status = $application->run($input, $output);
+            if (0 == $status) {
+                $this->info('Command success: ' . $commandAndParams['command']);
+            } else {
+                $this->err('Command failure: ' . $commandAndParams['command']);
+            }
+            sleep(2);
```
Comment (igorbga) [inline src/Controller/DefaultController.php:206]: I think we might be able to get rid of this, and if we are not we should at least put a comment.
Read my next comment about redirect.

File: src/Controller/DefaultController.php [hunk 2]
```diff
@@ -2266,6 +2287,7 @@ public function manageParametersAction(Request $request)
                     $t->trans('Parameters updated', array(), 'BinovoElkarBackup')
                 );
             }
+            $this->clearCache();
             $result = $this->redirect($this->generateUrl('manageParameters'));
```
Comment (igorbga) [inline src/Controller/DefaultController.php:2291]: A long shot about why we need the sleep:

redirect seems to send an HTTP redirect and it seems that if execution is fast enough the deletion is not still complete and the new request sees the old parameters. That seems weird and suggests some kind of race condition at "file system" level but that's what it seems to be.
In PHP 8.1 they have just added Fsync (https://php.watch/versions/8.1/fsync-fdatasync) that might have solved the issue but that's another story.

It seems that there is a way of forwarding a request instead of redirecting: https://symfony.com/doc/4.4/controller/forwarding.html

This is quite counterintuitive but who knows, maybe if you are in the exact same request/process that have just deleted the cache it sees the new one.

File: src/Controller/DefaultController.php [hunk 3]
```diff
@@ -186,8 +188,27 @@ protected function isAutoFsAvailable()
      */
     protected function clearCache()
     {
-        $realCacheDir = $this->cacheDir;
-        $this->cacheClearer->clear($realCacheDir);
+        try {
+            $commandAndParams = [
+                'command' => 'cache:clear',
+                '--env' => 'prod'
```
Comment (igorbga) [inline src/Controller/DefaultController.php:194]: Don't do that, leave it delete the actual environment.
I know that for dev this is unneede but in some environments, admitedly mostly only in prod, you might have "optimized" installations that do not include some classes etc. and you might have issues when trying to cache clear them.
So I just wouldn't take the risk. The command will know what environment to delete.

File: src/Controller/DefaultController.php [hunk 4]
```diff
@@ -186,8 +188,27 @@ protected function isAutoFsAvailable()
...
+            ];
```
Comment (igorbga) [inline src/Controller/DefaultController.php:195]: Cache clear command has an option for not warming up the cache after deletion. If you use it the next request will force the creation of the cache at the expense of taking a little more time.

Maybe this way you can get rid of the horrible `sleep`

**Review by igorbga — CHANGES_REQUESTED** [review]
This is the place were cacheDir is injected: 

https://github.com/elkarbackup/elkarbackup/blob/b1587b6d0b38d59673203390da1960de127feee9/config/services.yaml#L33

This injects the parameter to all controller which is a really horrible idea, but as we only have one controller (another horrible idea) it just works. If it's not needed you can remove it there.

File: src/Controller/DefaultController.php (hunk 2 above)
Comment (elacunza) [reply src/Controller/DefaultController.php:2291]: This doesn't work, it gets the old parameters (I think they're already loaded from cache).

File: src/Controller/DefaultController.php (hunk 4 above)
Comment (elacunza) [reply src/Controller/DefaultController.php:195]: This doesn't work either. Tried with --no-warmup .

File: src/Controller/DefaultController.php (hunk 1 above)
Comment (elacunza) [reply src/Controller/DefaultController.php:206]: Tried both options without success. I don't want to spend more time with this, sleep will have to do unless someone else finds a better solution. Thanks for your suggestions!

File: src/Controller/DefaultController.php (hunk 3 above)
Comment (elacunza) [reply src/Controller/DefaultController.php:194]: Done, thanks, seems reasonable.

**Comment by elacunza** [comment]
I will merge now if you don't have additional comments :)

File: src/Controller/DefaultController.php (hunk 1 above)
Comment (igorbga) [reply src/Controller/DefaultController.php:210]: At least a comment for the sleep please, otherwise the next one coming here will be tempted to delete it.

**Comment by igorbga** [comment]
Go ahead, merge it.
